#  https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Given an archive of multiple files to process
  When the archive is placed in a bucket
  Then the files in the archive are examined
  and the words in the sentence fragments are counted in a dataframe
  and the data frame is exported to a configured target folder
  and the processed archive is moved to a configured bucket.'
Globals:
  Function:
    Runtime: 'python3.6'
    MemorySize: 64
    Timeout: 10
Resources:
  HopperBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'serverless-wordcount-hopper'
  ResultBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'serverless-wordcount-result'
  ArchiveBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'serverless-wordcount-archive'
  CopyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'ServerlessWordCount'
      Description: ''
      Handler: 'lambda_wordcount.lambda_handler'
      CodeUri: ./target/dist
      Policies: AmazonS3FullAccess
      Environment:
        Variables:
          ResultBucket:  'serverless-wordcount-result'
          ResultPostfix: '-result.json'
          ArchiveBucket: 'serverless-wordcount-archive'
      Events:
        BucketEvent:
          Type: S3
          Properties:
            Bucket: !Ref HopperBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: 'suffix'
                    Value: '.tar.gz'
